export const RESUME = {
  name: "Ayabulela Mahlathini",
  title: "Software Engineer, Full-Stack",
  contact: {
    phone: "+27 84 908 6628",
    email: "ayabulelamahlathini@gmail.com",
    location: "Cape Town, South Africa",
    linkedin: "your_linkedin_profile",
    github: "your_github_profile",
    website: "ayamash.tech",
  },
  summary:
    "I’m a Full Stack Engineer with 5+ years of experience solving problems, writing clean code, and working on products that make an impact. With a deep love for frontend development and UI/UX, I specialize in crafting sleek, high-performance applications using React, TypeScript, and Next.js, while also keeping things solid on the backend. I’m a fast learner and highly adaptive to new languages and technologies, allowing me to pick up new tools quickly and build efficient, scalable solutions. For me, great software is more than just code—it’s about crafting an experience that’s as enjoyable to use as it is to build.",
  experience: [
    {
      title: "Software Engineer, Full-Stack",
      company: "Mercedes-Benz South Africa",
      location: "East London, ZA",
      dates: "Dec. 2021 - Present",
      description: [
        "Engineered customer-facing web applications using React.js and TypeScript, resulting in a 40% increase in user engagement and a 25% improvement in sprint completion rates.",
        "Led UI/UX design and front-end development, ensuring design fidelity and optimal performance, while increasing user satisfaction and feedback contribution by 40%.",
        "Spearheaded the integration of GraphQL, enhancing data retrieval efficiency and boosting application performance by 30%.",
        "Mentored interns and new hires, fostering a culture of knowledge sharing and team growth.",
        "Contributed to Agile coaching initiatives, leading to a 20% increase in development cycle efficiency.",
        "Collaborated effectively with.NET developers and DevOps teams to deliver cohesive and scalable solutions.",
        "Maintained high code quality standards through rigorous code reviews and comprehensive testing.",
      ],
    },
    {
      title: "Junior Software Developer",
      company: "Autumn Leaf IT",
      location: "Cape Town, ZA",
      dates: "Aug. 2021 - Nov. 2021",
      description: [
        "Developed full-stack web applications using React.js, GraphQL, and AWS services (Amplify, Lambda, Elastic Beanstalk).",
        "Researched and integrated new technologies, improving development efficiency by 20%.",
        "Supported deployment processes, expanding cloud computing knowledge and experience.",
      ],
    },
    {
      title: "Intern Cloud Support Associate",
      company: "Amazon Web Services",
      location: "Cape Town, ZA",
      dates: "Jan 2021 - Jun. 2021",
      description: [
        "Provided cloud support for AWS services (EC2, S3, RDS) via forums and ticketing systems.",
        "Troubleshot and resolved cloud infrastructure, database, and networking issues.",
        "Contributed to AWS forums by answering customer inquiries and providing solutions.",
      ],
    },
  ],
  technicalSkills: [
    "React.js",
    "Next.js",
    "TypeScript",
    "JavaScript",
    "Tailwind",
    "GraphQL",
    "RESTful APIs",
    "Material-UI",
    "UI/UX Design (Figma)",
    "Git",
    "Spring Boot",
    "Azure DevOps",
    "Docker",
    ".NET Web API",
    "Jest",
    "AWS",
    "React Testing Library",
    "Agile Methodologies (Scrum)",
  ],
  keyStrengths: [
    "Full-Stack Development",
    "UI/UX Design",
    "Agile Development",
    "Problem-Solving",
    "Collaboration",
    "Mentorship",
    "Communication",
    "Continuous Learning",
  ],
  education: [
    {
      degree: "Diploma: ICT in Applications Development",
      institution: "Cape Peninsula University of Technology",
      location: "Cape Town, ZA",
      dates: "2018 - 2020",
      relevantModules: [
        "Software Engineering and Development",
        "Information Systems",
        "UI/UX Design",
        "Multimedia Technology",
        "Networking",
        "Project Management",
        "Professional Practice",
        "Information Management",
      ],
    },
    {
      degree: "National Senior Certificate",
      institution: "Sakhululeka High School",
      location: "Fort Beaufort, ZA",
      dates: "Jan 2009 - Dec 2013",
    },
  ],
  certifications: [
    {
      name: "Meta: Front-End Developer Professional Certificate",
      issued: "Jan 2025",
      issuer: "Meta",
      expiration: "No official expiration Date",
    },
    {
      name: "Microsoft Certified: Azure Fundamentals",
      issued: "Jul 2024",
      issuer: "Microsoft Corporation",
      expiration: "May 2025",
    },
    {
      name: "AWS: Certified Cloud Practitioner",
      issued: "March 2021",
      issuer: "Amazon Web Services, Inc.",
      expiration: "March 2024",
    },
  ],
  volunteering: [
    {
      title: "IT Director",
      organization: "ENACTUS CPUT",
      location: "Cape Town, ZA",
      dates: "Aug. 2019 - Feb 2020",
      description: [
        "Led the identification and implementation of technical solutions for projects aligned with the UN’s Sustainable Development Goals (SDGs)",
        "Provided technical support and mentorship to team members, fostering a culture of innovation, collaboration, and excellence",
        "Streamlined onboarding and project execution by introducing efficient digital solutions, leading to the 2019 Most Outstanding Growth Award at the Enactus National Competition",
        "Conducted technical feasibility analyses to ensure scalability and alignment with project objectives",
        "Coordinated and managed technical training for team members, upskilling them in areas such as graphic design, video editing, and app development.",
      ],
    },
    {
      title: "Digital Designer / Technical Advisor",
      organization: "ENACTUS CPUT",
      location: "Cape Town, ZA",
      dates: "March. 2019 - Jul. 2019",
      description: [
        "Invited to attend and actively participate in the MTN Design Thinking Bootcamp, gaining hands-on experience in the design process from empathy to prototype delivery",
        "Played a key role in Enactus CPUT’s success at the 2019 MTN ICT Challenge, contributing to the winning prototype for the FindaDoctor mobile app through expertise in Design Thinking methodology and technical execution",
        "Led UI/UX design initiatives, creating intuitive and visually appealing interfaces for key projects",
        "Designed, developed, and published the UniMoola Varsity Market solution, significantly enhancing project outreach and impact across university campuses",
        "Designed and produced visual media assets for competition submissions, contributing to Enactus CPUT’s successful representation at the national level",
        "Managed and coordinated the technical aspects of presentation media for Enactus CPUT at the National Competition, ensuring flawless execution and the seamless delivery of key presentations.",
      ],
    },
  ],
  projects: [
    {
      name: "E-Pharmacy Delivery System",
      organization: "Cape Peninsula University of Technology",
      location: "Cape Town, ZA",
      dates: "Feb. 2020 - Dec. 2020",
      description: [
        "Took ownership of the web and mobile frontends using React and React Native, integrating with a team-built API",
        "Gathered requirements and designed UML diagrams to align the system with user needs",
        "Developed database design to support the e-commerce platform’s scalability",
        "Executed full-stack development with Spring Boot, MySQL, and JavaScript frameworks",
        "Self-taught React to complete the project outside of the curriculum",
        "Presented the project, showcasing development and integration outcomes.",
      ],
    },
    {
      name: "MHEALTH Booking System",
      organization: "Cape Peninsula University of Technology",
      location: "Cape Town, ZA",
      dates: "Jun 2019 - Dec 2019",
      description: [
        "Applied SDLC and Design Thinking methodologies to empathize with users, define real-life problems, and ideate innovative solutions",
        "Designed and prototyped user-friendly UI/UX, improving user engagement and enhancing system usability",
        "Developed a comprehensive System Requirements Specification (SRS) document, providing a solid foundation for successful system development",
        "Delivered a project presentation, effectively communicating design concepts, user insights, and system specifications to stakeholders.",
      ],
    },
  ],
};
